# Model arguments
model_name_or_path: iqwiki-kor/Qwen2.5-7B-distill-SFT-DPO-beta0.01-Iter1-v2
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: iqwiki-kor/Q2.5-7B-dist-op-pref-iter2-v2
dataset_split: train
preprocessing_num_workers: 32

# GRPO trainer config
bf16: true
do_eval: false
tf32: true
torch_compile: true
beta: 1.0
optim: paged_adamw_8bit
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: iqwiki-kor/Qwen2.5-7B-distill-SFT-DPO-beta1.0-Iter2-v2
learning_rate: 5.0e-7
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
max_steps: -1
num_train_epochs: 1
output_dir: /data/hf_cache/Qwen2.5-7B-distill-SFT-DPO-beta1.0-Iter2-v2
per_device_train_batch_size: 2
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1

# Hub
push_to_hub: true
hub_private_repo: true


# GRPO 
### https://github.com/huggingface/trl/blob/main/trl/trainer/grpo_config.py
max_prompt_length: 512
num_generations: 8 
temperature: 0.9
max_completion_length: 512
use_vllm: true
vllm_device: auto
vllm_max_model_len: 512

learning_rate: 1.0e-6
beta: 0.04
num_iterations: 1
epsilon: 0.2
reward_weights: None
# sync_ref_model: 
# ref_model_mixup_alpha: 
# ref_model_sync_steps: 
log_completions: true