# Model arguments
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: iqwiki-kor/MP-86k
dataset_split:
- train
preprocessing_num_workers: 16
auto_insert_empty_system_msg: false

# RewardTrainer config
bf16: true
do_eval: false
tf32: true
torch_compile: true
optim: paged_adamw_8bit
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 1.0e-5
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_length: 2048
max_steps: -1
num_train_epochs: 1
overwrite_output_dir: true
per_device_train_batch_size: 8
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1

# Hub
push_to_hub: false