# Model arguments
model_name_or_path: Qwen/Qwen2.5-Math-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: nlee-208/Ko-LIMO
dataset_split: train
preprocessing_num_workers: 16
auto_insert_empty_system_msg: false
insert_cot_system_msg: true

# SFT trainer config
bf16: true
do_eval: false
optim: paged_adamw_8bit
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: nlee-208/Q25-M-1.5B-IT-KoLIMO-5ep
learning_rate: 5.0e-6
log_level: info
logging_steps: 2  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 16384
max_steps: -1
num_train_epochs: 5
output_dir: /mnt/tmp/hf_cache/Q25-M-1.5B-IT-KoLIMO-5ep
overwrite_output_dir: true
per_device_train_batch_size: 1
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "epoch"
seed: 4
warmup_ratio: 0.0

# Hub
push_to_hub: true
hub_private_repo: true
